/* ==========================================================================
   QuizSystem - Advanced EdTech Question Dataset
   Categories: Java, OOP, DBMS, SQL, HTML/CSS, JavaScript, OS, Computer Networks
   Fields per question:
   - id, category, topic, difficulty, question, options, correct
   - hint, explanation, concept, commonMistake, quickTip
   - isTricky, trickyExplanation
   - interviewTesting, interviewFollowUp
   - videoLink
   ========================================================================== */

const QUESTION_DATABASE = {
    java: [
        {
            id: "j1",
            category: "Java",
            topic: "Java Basics",
            difficulty: "Easy",
            question: "Which keyword is used to declare a class in Java?",
            options: ["struct", "class", "interface", "define"],
            correct: 1,
            hint: "Think about the foundational keyword used in Java to encapsulate data and methods into a blueprint.",
            explanation: "The 'class' keyword is used in Java to define a user-defined blueprint from which individual objects are instantiated.",
            concept: "Classes & Blueprint Definition in Object-Oriented Java.",
            commonMistake: "Confusing Java's 'class' with C language's 'struct' or preprocessor '#define'.",
            quickTip: "Every standalone Java program requires at least one class definition.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests basic knowledge of Java syntax and object creation fundamentals.",
            interviewFollowUp: "What is the difference between a public class and a package-private class in Java?",
            videoLink: "https://www.youtube.com/watch?v=eIrMbAQSU34"
        },
        {
            id: "j2",
            category: "Java",
            topic: "Primitive Types",
            difficulty: "Easy",
            question: "What is the fixed memory size of a standard primitive 'int' data type in Java?",
            options: ["8 bits", "16 bits", "32 bits", "64 bits"],
            correct: 2,
            hint: "Java primitive integer sizes are fixed regardless of operating system architecture. It uses 4 bytes.",
            explanation: "In Java, an 'int' is a signed 32-bit primitive data type with a range from -2^31 to 2^31 - 1.",
            concept: "Fixed Primitive Data Types in Java Virtual Machine (JVM).",
            commonMistake: "Assuming primitive sizes change between 32-bit and 64-bit OS architectures (unlike C/C++).",
            quickTip: "Remember: byte (1 byte/8-bit), short (2 bytes), int (4 bytes/32-bit), long (8 bytes/64-bit).",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Assesses understanding of platform independence and JVM data specifications.",
            interviewFollowUp: "Why does Java guarantee fixed primitive sizes across all operating platforms?",
            videoLink: "https://www.youtube.com/watch?v=eIrMbAQSU34"
        },
        {
            id: "j3",
            category: "Java",
            topic: "Collections",
            difficulty: "Medium",
            question: "Which Java Collection class guarantees unique elements and automatically forbids duplicate entries?",
            options: ["ArrayList", "Vector", "HashSet", "LinkedList"],
            correct: 2,
            hint: "Think of the set data structure in mathematics where duplicate elements are automatically excluded.",
            explanation: "HashSet implements the Set interface, backed by a hashtable. It stores unique elements by using hashCode() and equals() to prevent duplicates.",
            concept: "Java Collections Framework - Set vs List interfaces.",
            commonMistake: "Confusing List implementations (ArrayList, LinkedList) which allow duplicates with Set implementations which forbid them.",
            quickTip: "List allows duplicates & maintains insertion order; Set enforces uniqueness.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Verifies knowledge of Java Collections contract implementations and hashing.",
            interviewFollowUp: "How does HashSet internally determine if two custom objects are duplicate?",
            videoLink: "https://www.youtube.com/watch?v=eIrMbAQSU34"
        },
        {
            id: "j4",
            category: "Java",
            topic: "Exception Handling",
            difficulty: "Medium",
            question: "Which unchecked exception is thrown by the JVM when an array is accessed with an index less than 0 or greater than equal to array length?",
            options: ["NullPointerException", "ArrayIndexOutOfBoundsException", "IllegalArgumentException", "ClassNotFoundException"],
            correct: 1,
            hint: "Consider what happens when you try to access an index outside the valid zero-based range [0, length - 1].",
            explanation: "ArrayIndexOutOfBoundsException is an unchecked RuntimeException thrown to indicate that an array has been accessed with an illegal index.",
            concept: "Java Exception Handling & Array Index Boundaries.",
            commonMistake: "Assuming array bounds errors are checked at compile time rather than runtime.",
            quickTip: "Valid array indices always satisfy: 0 <= index < array.length.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Evaluates exception handling taxonomy (Checked vs Unchecked exceptions).",
            interviewFollowUp: "What is the base superclass for all unchecked exceptions in Java?",
            videoLink: "https://www.youtube.com/watch?v=eIrMbAQSU34"
        },
        {
            id: "j5",
            category: "Java",
            topic: "Multithreading",
            difficulty: "Hard",
            question: "What happens if a thread invokes Object.wait() without holding the target object's monitor lock inside a synchronized block?",
            options: ["InterruptedException", "IllegalMonitorStateException", "ThreadDeath", "Deadlock"],
            correct: 1,
            hint: "To call wait(), notify(), or notifyAll(), a thread must first acquire the synchronized monitor lock.",
            explanation: "If a thread invokes wait() or notify() without owning the specified object's monitor lock, the JVM throws an unchecked IllegalMonitorStateException at runtime.",
            concept: "Java Concurrency & Inter-thread Communication Locks.",
            commonMistake: "Thinking wait() can be called anywhere in code without a synchronized block.",
            quickTip: "Always wrap wait() and notify() calls inside synchronized(object) blocks.",
            isTricky: true,
            trickyExplanation: "Many developers guess InterruptedException because wait() throws InterruptedException when interrupted, but failing to hold the lock throws IllegalMonitorStateException immediately!",
            interviewTesting: "Tests deep understanding of multi-threaded synchronized monitors and thread state transitions.",
            interviewFollowUp: "Why must wait() and notify() be called from within a synchronized context?",
            videoLink: "https://www.youtube.com/watch?v=eIrMbAQSU34"
        },
        {
            id: "j6",
            category: "Java",
            topic: "Strings & Immutability",
            difficulty: "Medium",
            question: "What is the result of comparing two String literals created via `String s1 = \"Java\"; String s2 = \"Java\";` using `s1 == s2`?",
            options: ["false", "true", "Compilation Error", "NullPointerException"],
            correct: 1,
            hint: "Java optimizes string storage using the String Constant Pool inside heap memory.",
            explanation: "`s1 == s2` evaluates to true because string literals are cached in the String Constant Pool, making both references point to the exact same memory address.",
            concept: "String Constant Pool and Reference Equality (==) vs Object Value Equality (.equals()).",
            commonMistake: "Thinking `==` always returns false for strings without considering literal pool caching.",
            quickTip: "Use `.equals()` for value comparison, but know that literals reference the same pool memory.",
            isTricky: true,
            trickyExplanation: "Developers are trained to never use `==` for strings, so they select `false`. However, string literals with identical values share the same pool reference!",
            interviewTesting: "Checks understanding of String Constant Pool memory optimization in JVM.",
            interviewFollowUp: "What happens if you create a string with `new String(\"Java\")` instead of a literal?",
            videoLink: "https://www.youtube.com/watch?v=eIrMbAQSU34"
        }
    ],

    oop: [
        {
            id: "o1",
            category: "OOP",
            topic: "Encapsulation",
            difficulty: "Easy",
            question: "Which OOP principle bundles data fields and operating methods into a single class unit while restricting direct access using private modifiers?",
            options: ["Abstraction", "Encapsulation", "Inheritance", "Polymorphism"],
            correct: 1,
            hint: "Think of a protective capsule that hides internal state behind getter and setter methods.",
            explanation: "Encapsulation is the bundling of data attributes and methods operating on that data within a single class, hiding internal implementation details using private access modifiers.",
            concept: "Object-Oriented Programming (OOP) Data Encapsulation.",
            commonMistake: "Confusing Encapsulation (data hiding via private fields) with Abstraction (hiding implementation complexity via interfaces).",
            quickTip: "Encapsulation = Data Hiding + Protective Access Modifiers (private fields + public getters/setters).",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests knowledge of foundational Object-Oriented design pillars.",
            interviewFollowUp: "How does encapsulation improve code maintainability and data validation?",
            videoLink: "https://www.youtube.com/watch?v=pTB0EiLXUC8"
        },
        {
            id: "o2",
            category: "OOP",
            topic: "Polymorphism",
            difficulty: "Medium",
            question: "Which OOP concept allows the same method call to exhibit different execution behaviors depending on the actual runtime object instance?",
            options: ["Polymorphism", "Encapsulation", "Inheritance", "Abstraction"],
            correct: 0,
            hint: "The word originates from Greek meaning 'many forms'. It enables dynamic method overriding.",
            explanation: "Polymorphism allows objects of different classes to respond to the same method invocation in their own unique way (e.g., Shape.draw() called on Circle or Square).",
            concept: "Dynamic Method Dispatch & Runtime Polymorphism.",
            commonMistake: "Confusing compile-time polymorphism (Method Overloading) with runtime polymorphism (Method Overriding).",
            quickTip: "Polymorphism = One Interface, Multiple Runtime Behaviors.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Verifies comprehension of method overriding and late binding at runtime.",
            interviewFollowUp: "What is the difference between compile-time overloading and runtime overriding?",
            videoLink: "https://www.youtube.com/watch?v=pTB0EiLXUC8"
        },
        {
            id: "o3",
            category: "OOP",
            topic: "Interfaces & Abstract Classes",
            difficulty: "Hard",
            question: "What is the primary inheritance distinction between an Interface and an Abstract Class in Java?",
            options: [
                "A class can implement multiple interfaces but extend only one class",
                "Interfaces can store mutable non-final instance fields",
                "Abstract classes cannot define constructors",
                "Interfaces allow private instance variable state"
            ],
            correct: 0,
            hint: "Consider Java's single inheritance constraint for classes versus multiple contract capabilities for interfaces.",
            explanation: "Java supports single class inheritance (a class can extend only one superclass/abstract class) but multiple interface implementation (a class can implement multiple interfaces).",
            concept: "Multiple Interface Implementation vs Single Class Inheritance.",
            commonMistake: "Believing abstract classes cannot have constructors (they do, to initialize superclass state).",
            quickTip: "Extend 1 Abstract Class ('IS-A'); Implement Multiple Interfaces ('CAN-DO').",
            isTricky: true,
            trickyExplanation: "Candidates often confuse interface features after Java 8/9 (default and private methods) with state storage rules. Interfaces still cannot hold instance state!",
            interviewTesting: "Evaluates architectural decision-making when designing class hierarchies.",
            interviewFollowUp: "When should you choose an abstract class over an interface in system design?",
            videoLink: "https://www.youtube.com/watch?v=pTB0EiLXUC8"
        },
        {
            id: "o4",
            category: "OOP",
            topic: "Inheritance",
            difficulty: "Easy",
            question: "Which keyword is used in Java by a child subclass to inherit from a parent superclass?",
            options: ["implements", "extends", "inherits", "super"],
            correct: 1,
            hint: "Think about extending the capability of a base class.",
            explanation: "The 'extends' keyword establishes an IS-A relationship where the subclass inherits attributes and methods from the superclass.",
            concept: "Single Inheritance & Code Reusability.",
            commonMistake: "Confusing 'extends' (for classes) with 'implements' (for interfaces).",
            quickTip: "Class extends Class | Class implements Interface.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests fundamental syntax for object inheritance.",
            interviewFollowUp: "Does Java support multiple inheritance of classes? Why or why not?",
            videoLink: "https://www.youtube.com/watch?v=pTB0EiLXUC8"
        },
        {
            id: "o5",
            category: "OOP",
            topic: "Abstraction",
            difficulty: "Medium",
            question: "What is the main goal of Abstraction in Object-Oriented Software Design?",
            options: [
                "Hiding internal implementation complexity and showing only essential public features",
                "Compressing source code files",
                "Encrypting object memory locations",
                "Preventing class instantiation permanently"
            ],
            correct: 0,
            hint: "Focus on reducing complexity by exposing high-level contracts while concealing low-level operational details.",
            explanation: "Abstraction focuses on showing essential behavior to users while hiding background implementation details, typically implemented using abstract classes and interfaces.",
            concept: "System Abstraction & Boundary Interfaces.",
            commonMistake: "Thinking abstraction and encapsulation are identical concepts.",
            quickTip: "Abstraction = Hiding Complexity | Encapsulation = Hiding Sensitive Data.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Assesses software engineering design abstraction capabilities.",
            interviewFollowUp: "Give a real-world example of abstraction (e.g. driving a car without knowing engine mechanics).",
            videoLink: "https://www.youtube.com/watch?v=pTB0EiLXUC8"
        }
    ],

    dbms: [
        {
            id: "db1",
            category: "DBMS",
            topic: "DBMS Basics",
            difficulty: "Easy",
            question: "Which database component uniquely identifies each record/row in a relational table?",
            options: ["Foreign Key", "Primary Key", "Candidate Key", "Composite Key"],
            correct: 1,
            hint: "This key constraint must contain unique values and cannot contain NULL values.",
            explanation: "A Primary Key is a column or set of columns that uniquely identifies each row in a database table. Primary keys must contain UNIQUE values and cannot contain NULL.",
            concept: "Relational Database Integrity Constraints & Keys.",
            commonMistake: "Confusing Primary Key (must be non-null & unique) with Foreign Key (references another table's primary key).",
            quickTip: "Primary Key = UNIQUE + NOT NULL constraint.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests knowledge of database relational design and table constraints.",
            interviewFollowUp: "Can a relational table have multiple Primary Keys? What about Unique Keys?",
            videoLink: "https://www.youtube.com/watch?v=HXV3zeQKqGY"
        },
        {
            id: "db2",
            category: "DBMS",
            topic: "Transactions & ACID",
            difficulty: "Medium",
            question: "What does the 'A' in ACID properties of transaction management guarantee?",
            options: [
                "Atomicity: Either all operations of a transaction execute completely or none execute at all",
                "Accuracy: Data values match real world metrics",
                "Availability: Database is reachable 24/7",
                "Authorization: User permissions are verified"
            ],
            correct: 0,
            hint: "Atomicity ensures the 'All-or-Nothing' rule during multi-step database transactions.",
            explanation: "Atomicity guarantees that all transaction statements execute successfully as a single atomic unit. If any operation fails, the entire transaction is rolled back.",
            concept: "ACID Transaction Guarantees & Transaction Rollbacks.",
            commonMistake: "Thinking Atomicity means execution speed rather than all-or-nothing completion.",
            quickTip: "Atomicity = All or Nothing | Durability = Permanent Storage.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Verifies understanding of transaction reliability and crash safety.",
            interviewFollowUp: "How do relational databases implement Atomicity using write-ahead logs (WAL)?",
            videoLink: "https://www.youtube.com/watch?v=HXV3zeQKqGY"
        },
        {
            id: "db3",
            category: "DBMS",
            topic: "Normalization",
            difficulty: "Hard",
            question: "A table is in Second Normal Form (2NF) if it is already in 1NF and satisfies which additional condition?",
            options: [
                "No partial dependencies (every non-prime attribute is fully functionally dependent on the entire primary key)",
                "No transitive dependencies exist",
                "All multi-valued attributes are removed",
                "Every determinant is a super key"
            ],
            correct: 0,
            hint: "2NF eliminates partial functional dependency where an attribute depends on only part of a composite primary key.",
            explanation: "2NF requires 1NF compliance plus the removal of partial dependencies. Every non-prime attribute must depend on the whole candidate primary key, not just a subset.",
            concept: "Database Normalization & Functional Dependency Rules (1NF -> 2NF -> 3NF -> BCNF).",
            commonMistake: "Confusing 2NF (eliminates partial dependency) with 3NF (eliminates transitive dependency).",
            quickTip: "1NF: Atomic values | 2NF: No partial key dependency | 3NF: No transitive dependency.",
            isTricky: true,
            trickyExplanation: "Candidates frequently swap the definitions of 2NF and 3NF. 2NF targets partial key dependencies; 3NF targets transitive dependencies between non-key attributes!",
            interviewTesting: "Assesses relational schema design and normalization mechanics.",
            interviewFollowUp: "What is BCNF and how does it differ from 3NF?",
            videoLink: "https://www.youtube.com/watch?v=HXV3zeQKqGY"
        },
        {
            id: "db4",
            category: "DBMS",
            topic: "Keys & Relationships",
            difficulty: "Easy",
            question: "Which key establishes a link/relationship between data in two relational tables?",
            options: ["Super Key", "Foreign Key", "Primary Key", "Candidate Key"],
            correct: 1,
            hint: "This key in a child table points directly to the Primary Key in a parent table.",
            explanation: "A Foreign Key is a field in one table that refers to the Primary Key in another table, ensuring referential integrity between linked datasets.",
            concept: "Referential Integrity & Table Relationships.",
            commonMistake: "Believing a Foreign Key must be unique in the child table (it can have duplicate foreign references).",
            quickTip: "Foreign Key maintains referential integrity across related tables.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests understanding of table relationships (1-to-1, 1-to-N, N-to-M).",
            interviewFollowUp: "What happens when you attempt to delete a parent record that has linked Foreign Keys in child records?",
            videoLink: "https://www.youtube.com/watch?v=HXV3zeQKqGY"
        }
    ],

    sql: [
        {
            id: "s1",
            category: "SQL",
            topic: "SQL Queries",
            difficulty: "Easy",
            question: "Which SQL clause is used to filter records and return only those rows that fulfill specified boolean conditions?",
            options: ["GROUP BY", "WHERE", "ORDER BY", "HAVING"],
            correct: 1,
            hint: "This filtering clause is evaluated BEFORE any GROUP BY aggregation takes place.",
            explanation: "The WHERE clause is used to filter records in a SQL query based on specified comparison or logical conditions.",
            concept: "SQL Query Execution Lifecycle & Filtering.",
            commonMistake: "Using HAVING instead of WHERE for filtering individual non-aggregated table rows.",
            quickTip: "WHERE filters rows before aggregation; HAVING filters aggregate groups after GROUP BY.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests standard SQL query clause syntax and execution order.",
            interviewFollowUp: "What is the complete execution order of clauses in a SQL SELECT statement?",
            videoLink: "https://www.youtube.com/watch?v=HXV3zeQKqGY"
        },
        {
            id: "s2",
            category: "SQL",
            topic: "Joins",
            difficulty: "Hard",
            question: "Which SQL JOIN returns all rows from the Left table, along with matching rows from the Right table, filling NULL for non-matching right records?",
            options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
            correct: 1,
            hint: "It preserves every record from the table specified on the left side of the JOIN keyword.",
            explanation: "A LEFT (OUTER) JOIN returns all records from the left table and matched records from the right table. Unmatched right table columns return NULL values.",
            concept: "Relational Set Operations & SQL Outer Join Types.",
            commonMistake: "Thinking LEFT JOIN discards left records that do not match the right table (that is INNER JOIN behavior).",
            quickTip: "LEFT JOIN = All Left rows + Matching Right rows (or NULLs).",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Verifies ability to combine data from multiple relational tables correctly.",
            interviewFollowUp: "How can you write a query using LEFT JOIN to find rows in Table A that have NO match in Table B?",
            videoLink: "https://www.youtube.com/watch?v=HXV3zeQKqGY"
        },
        {
            id: "s3",
            category: "SQL",
            topic: "Grouping & Aggregation",
            difficulty: "Medium",
            question: "Which SQL clause is used to filter grouped aggregated data resulting from a GROUP BY query?",
            options: ["WHERE", "HAVING", "ORDER BY", "FILTER BY"],
            correct: 1,
            hint: "WHERE filters individual rows before grouping, while this clause filters groups after aggregate calculation.",
            explanation: "The HAVING clause was added to SQL because the WHERE keyword could not be used with aggregate functions (like SUM, COUNT, AVG).",
            concept: "Aggregate Functions & Group Filtering.",
            commonMistake: "Attempting to use `WHERE COUNT(id) > 5` instead of `HAVING COUNT(id) > 5`.",
            quickTip: "Use WHERE for row conditions; use HAVING for aggregate functions.",
            isTricky: true,
            trickyExplanation: "Beginners often write `WHERE SUM(price) > 100` which throws a syntax error. Aggregate functions are only valid inside HAVING or SELECT clauses!",
            interviewTesting: "Assesses SQL query construction involving group metrics.",
            interviewFollowUp: "Can you use both WHERE and HAVING in the exact same SQL query? Explain.",
            videoLink: "https://www.youtube.com/watch?v=HXV3zeQKqGY"
        },
        {
            id: "s4",
            category: "SQL",
            topic: "SQL Sorting",
            difficulty: "Easy",
            question: "Which keyword is used in SQL to sort query results in descending order?",
            options: ["ORDER BY col DESC", "SORT BY col DOWN", "GROUP BY col DESC", "ARRANGE DESC"],
            correct: 0,
            hint: "Combine the ORDER BY clause with the abbreviation for descending.",
            explanation: "The `ORDER BY column_name DESC` clause sorts the returned records in descending order (highest to lowest or Z to A).",
            concept: "SQL Result Set Sorting (ASC vs DESC).",
            commonMistake: "Using non-standard terms like 'DOWN' or 'DECREASING' instead of 'DESC'.",
            quickTip: "Default sorting is ASC; use DESC explicitly for reverse order.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests basic query result formatting.",
            interviewFollowUp: "How are NULL values handled during ORDER BY ASC vs DESC in SQL databases?",
            videoLink: "https://www.youtube.com/watch?v=HXV3zeQKqGY"
        }
    ],

    html_css: [
        {
            id: "hc1",
            category: "HTML/CSS",
            topic: "HTML Basics",
            difficulty: "Easy",
            question: "Which HTML5 semantic element should be used to enclose major navigation link lists?",
            options: ["<header>", "<nav>", "<section>", "<aside>"],
            correct: 1,
            hint: "This tag represents a section of a page whose purpose is to provide navigation links.",
            explanation: "The <nav> element is intended for major blocks of navigation links, improving accessibility and SEO structure.",
            concept: "HTML5 Semantic Elements & Web Accessibility.",
            commonMistake: "Wrapping navigation menus inside generic <div> containers instead of semantic <nav> tags.",
            quickTip: "Use <nav> for main site menus, breadcrumbs, and pagination links.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Evaluates modern HTML5 semantic markup and web accessibility standards.",
            interviewFollowUp: "Why are semantic HTML tags preferred over <div> elements for SEO and screen readers?",
            videoLink: "https://www.youtube.com/watch?v=mU6anWqZJcc"
        },
        {
            id: "hc2",
            category: "HTML/CSS",
            topic: "Flexbox",
            difficulty: "Medium",
            question: "In CSS Flexbox, which property aligns flex items along the cross axis (perpendicular to the main axis)?",
            options: ["justify-content", "align-items", "flex-direction", "align-content"],
            correct: 1,
            hint: "justify-content handles main-axis alignment, while this property handles cross-axis alignment.",
            explanation: "align-items specifies the default alignment for items inside a flex container along the cross axis (vertically in row layout).",
            concept: "CSS Flexible Box Layout Model (Main Axis vs Cross Axis Alignment).",
            commonMistake: "Confusing `justify-content` (main axis) with `align-items` (cross axis).",
            quickTip: "justify-content = Main Axis | align-items = Cross Axis.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests mastery of CSS Flexbox positioning and layout alignment.",
            interviewFollowUp: "What happens to the main axis when `flex-direction: column` is set?",
            videoLink: "https://www.youtube.com/watch?v=mU6anWqZJcc"
        },
        {
            id: "hc3",
            category: "HTML/CSS",
            topic: "Box Model & Specificity",
            difficulty: "Hard",
            question: "Which CSS box-sizing property value ensures that an element's total width includes padding and borders?",
            options: ["content-box", "border-box", "padding-box", "margin-box"],
            correct: 1,
            hint: "With this property value, width = content + padding + border without expanding the calculated element footprint.",
            explanation: "`box-sizing: border-box` tells the browser to account for any border and padding in the values specified for an element's width and height.",
            concept: "CSS Box Model & Element Layout Dimensions.",
            commonMistake: "Assuming `content-box` (browser default) includes padding in the declared width property.",
            quickTip: "Apply `* { box-sizing: border-box; }` in CSS resets to prevent layout distortion.",
            isTricky: true,
            trickyExplanation: "Under default `content-box`, setting `width: 100px; padding: 10px;` produces a total rendered width of 120px! `border-box` locks total width to 100px.",
            interviewTesting: "Verifies understanding of CSS rendering engine calculations.",
            interviewFollowUp: "Explain CSS Selector Specificity scoring (Inline vs ID vs Class vs Element).",
            videoLink: "https://www.youtube.com/watch?v=mU6anWqZJcc"
        }
    ],

    javascript: [
        {
            id: "js1",
            category: "JavaScript",
            topic: "Variables & Scope",
            difficulty: "Easy",
            question: "Which keyword is used in ES6 JavaScript to declare block-scoped variables that cannot be reassigned?",
            options: ["var", "let", "const", "static"],
            correct: 2,
            hint: "This keyword creates a block-scoped immutable binding that prevents reassignment.",
            explanation: "`const` declarations create read-only block-scoped references that cannot be reassigned after initialization.",
            concept: "ES6 Variable Scoping (var vs let vs const).",
            commonMistake: "Thinking `const` makes objects completely immutable (object properties can still be mutated, but reference cannot be reassigned).",
            quickTip: "Use `const` by default; use `let` when reassignment is expected.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Assesses foundational understanding of modern JavaScript variable declarations.",
            interviewFollowUp: "Can you mutate properties of an object declared with `const`? Why?",
            videoLink: "https://www.youtube.com/watch?v=W6NZfCO5SIk"
        },
        {
            id: "js2",
            category: "JavaScript",
            topic: "Closures",
            difficulty: "Hard",
            question: "What is a Closure in JavaScript?",
            options: [
                "A function bundled together with references to its surrounding lexical scope environment",
                "A method to close active DOM event listeners",
                "A private class keyword added in ES2022",
                "An event loop exit signal handler"
            ],
            correct: 0,
            hint: "Focus on how an inner function retains access to variables declared in its outer scope even after outer execution finishes.",
            explanation: "A closure gives an inner function access to its outer function's scope variables, preserving those variables even after the outer function has returned.",
            concept: "JavaScript Execution Context, Lexical Scoping & Closures.",
            commonMistake: "Thinking closures copy variable values at creation time rather than retaining reference memory.",
            quickTip: "Closure = Inner Function + Outer Lexical Scope Memory.",
            isTricky: true,
            trickyExplanation: "Developers often think closures copy static values, but they retain live references to variables in outer lexical scopes!",
            interviewTesting: "Tests deep knowledge of JavaScript scoping and memory execution context.",
            interviewFollowUp: "How can closures be used to create private variables in JavaScript modules?",
            videoLink: "https://www.youtube.com/watch?v=W6NZfCO5SIk"
        },
        {
            id: "js3",
            category: "JavaScript",
            topic: "Promises & Async",
            difficulty: "Medium",
            question: "What state is a JavaScript Promise in after `resolve(data)` is invoked successfully?",
            options: ["pending", "fulfilled", "rejected", "terminated"],
            correct: 1,
            hint: "A resolved promise transitions from pending to this completed success state.",
            explanation: "When a Promise resolves, its state changes from 'pending' to 'fulfilled', triggering attached `.then()` callbacks.",
            concept: "JavaScript Asynchronous Event Loop & Promise States.",
            commonMistake: "Confusing 'fulfilled' (resolved) with 'pending' or 'settled'.",
            quickTip: "Promise States: Pending -> Fulfilled (resolved) OR Rejected.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Evaluates asynchronous programming models in JavaScript.",
            interviewFollowUp: "What is the difference between microtasks (Promises) and macrotasks (setTimeout) in the JS Event Loop?",
            videoLink: "https://www.youtube.com/watch?v=W6NZfCO5SIk"
        }
    ],

    os: [
        {
            id: "os1",
            category: "OS",
            topic: "Deadlocks",
            difficulty: "Medium",
            question: "What is a Deadlock in Operating Systems concurrent processing?",
            options: [
                "A state where a set of processes are permanently blocked because each holds a resource and waits for another held by another process",
                "A hardware memory overflow exception",
                "A network timeout error during socket read",
                "A CPU thread starvation condition"
            ],
            correct: 0,
            hint: "Think of Coffman conditions: Mutual Exclusion, Hold & Wait, No Preemption, and Circular Wait.",
            explanation: "A Deadlock occurs when two or more processes cannot proceed because each is waiting for a resource held by the other, resulting in a circular wait condition.",
            concept: "Operating System Process Concurrency & Deadlock Coffman Conditions.",
            commonMistake: "Confusing Deadlock (permanent circular wait block) with Starvation (indefinite postponement).",
            quickTip: "Deadlock = Circular Wait where everyone waits for someone else indefinitely.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests knowledge of concurrency pitfalls and deadlock conditions.",
            interviewFollowUp: "What are the 4 necessary conditions for a deadlock to occur (Coffman conditions)?",
            videoLink: "https://www.youtube.com/watch?v=vBURTt97EkA"
        },
        {
            id: "os2",
            category: "OS",
            topic: "Memory Management",
            difficulty: "Hard",
            question: "What is Virtual Memory in Operating Systems?",
            options: [
                "A memory management technique that uses secondary disk storage to simulate additional physical RAM",
                "Dedicated GPU Video RAM allocation",
                "Cloud storage data caching",
                "ROM BIOS cache memory"
            ],
            correct: 0,
            hint: "It uses paging and disk swap space so execution addresses can exceed physical RAM size.",
            explanation: "Virtual Memory creates the illusion of a vast physical RAM memory space by swapping inactive memory pages between RAM and disk pagefile storage.",
            concept: "Operating System Virtual Memory, Page Tables & Demand Paging.",
            commonMistake: "Believing Virtual Memory is actual physical RAM hardware installed on the motherboard.",
            quickTip: "Virtual Memory = Physical RAM + Secondary Storage Pagefile Swap.",
            isTricky: true,
            trickyExplanation: "Candidates confuse Virtual Memory with CPU cache or VRAM. Virtual memory is an OS software abstraction backed by storage disk paging.",
            interviewTesting: "Assesses understanding of OS memory abstraction and paging mechanisms.",
            interviewFollowUp: "What is a Page Fault and how does the OS kernel handle it?",
            videoLink: "https://www.youtube.com/watch?v=vBURTt97EkA"
        },
        {
            id: "os3",
            category: "OS",
            topic: "CPU Scheduling",
            difficulty: "Medium",
            question: "Which CPU scheduling algorithm allocates execution time to processes in equal fixed time slices (time quanta)?",
            options: ["First-Come First-Served (FCFS)", "Round Robin (RR)", "Shortest Job First (SJF)", "Priority Scheduling"],
            correct: 1,
            hint: "Think of a circular queue where each process receives a turn for a small unit of CPU time.",
            explanation: "Round Robin scheduling assigns a fixed time quantum to each process in a cyclic queue, providing fair preemptive multi-tasking.",
            concept: "Preemptive CPU Scheduling Algorithms.",
            commonMistake: "Thinking Round Robin is non-preemptive like FCFS.",
            quickTip: "Round Robin uses time slices (quanta) for interactive time-sharing.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Evaluates process management and scheduling strategies.",
            interviewFollowUp: "What happens to context switching overhead when the Round Robin time quantum becomes extremely small?",
            videoLink: "https://www.youtube.com/watch?v=vBURTt97EkA"
        }
    ],

    cn: [
        {
            id: "cn1",
            category: "Computer Networks",
            topic: "OSI Model",
            difficulty: "Easy",
            question: "In the 7-layer OSI Model, which layer is responsible for logical IP addressing and packet routing across subnets?",
            options: ["Data Link Layer (Layer 2)", "Network Layer (Layer 3)", "Transport Layer (Layer 4)", "Session Layer (Layer 5)"],
            correct: 1,
            hint: "Routers operate at Layer 3 using logical IP addresses to forward packets across networks.",
            explanation: "The Network Layer (Layer 3) handles logical IP addressing, packet routing, and path determination across interconnected networks.",
            concept: "OSI 7-Layer Reference Model & Network Layer Routing.",
            commonMistake: "Confusing Layer 2 (Data Link - MAC addresses/Switches) with Layer 3 (Network - IP addresses/Routers).",
            quickTip: "Layer 2 = MAC/Switches | Layer 3 = IP/Routers | Layer 4 = Ports/TCP.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests core networking architecture and OSI layer responsibilities.",
            interviewFollowUp: "Which network device operates at Layer 2 vs Layer 3 of the OSI model?",
            videoLink: "https://www.youtube.com/watch?v=IPvYjXCsTg8"
        },
        {
            id: "cn2",
            category: "Computer Networks",
            topic: "Transport Layer",
            difficulty: "Medium",
            question: "Which Transport Layer protocol provides reliable, connection-oriented data transmission using a 3-way handshake?",
            options: ["UDP", "IP", "TCP", "ICMP"],
            correct: 2,
            hint: "This protocol uses SYN, SYN-ACK, ACK packets to establish a connection before data transfer.",
            explanation: "TCP (Transmission Control Protocol) is connection-oriented, offering reliable, ordered, and error-checked stream delivery.",
            concept: "Transport Layer Protocols - TCP vs UDP.",
            commonMistake: "Selecting UDP (which is connectionless and does not guarantee packet delivery).",
            quickTip: "TCP = Connection-oriented & Guaranteed Delivery | UDP = Fast & Connectionless.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Assesses transport protocol selection for software applications.",
            interviewFollowUp: "Explain the TCP 3-way handshake process (SYN, SYN-ACK, ACK).",
            videoLink: "https://www.youtube.com/watch?v=IPvYjXCsTg8"
        },
        {
            id: "cn3",
            category: "Computer Networks",
            topic: "IP Addressing & Subnetting",
            difficulty: "Hard",
            question: "What is the primary function of DNS (Domain Name System) on the Internet?",
            options: [
                "Translating human-readable domain names (e.g., example.com) into numerical IP addresses",
                "Encrypting HTTP traffic payload",
                "Assigning dynamic local IP addresses to host devices",
                "Filtering malicious network packets at the gateway"
            ],
            correct: 0,
            hint: "Think of DNS as the phonebook of the Internet.",
            explanation: "DNS translates domain names that humans can memorize into machine-readable IP addresses required for network routing.",
            concept: "Application Layer Protocols & Domain Resolution.",
            commonMistake: "Confusing DNS (name resolution) with DHCP (IP address assignment).",
            quickTip: "DNS = Domain to IP Translation | DHCP = Auto IP Assignment.",
            isTricky: false,
            trickyExplanation: "",
            interviewTesting: "Tests understanding of essential Internet application protocols.",
            interviewFollowUp: "What happens step-by-step when you type a URL into your browser address bar?",
            videoLink: "https://www.youtube.com/watch?v=IPvYjXCsTg8"
        }
    ]
};
